# Generated by Django 5.2.10 on 2026-02-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('ntn_number', models.CharField(max_length=50, unique=True, verbose_name='NTN Number')),
                ('ntn_expiry_date', models.DateField(verbose_name='NTN Expiry Date')),
                ('subscription_expiry_date', models.DateField()),
                ('tenant_prefix', models.CharField(help_text="Unique prefix used for asset encoding (e.g., 'ABC').", max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
